services:
  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379"

  zookeeper:
    image: zookeeper
    container_name: my-zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka-broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: my-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: chat-backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
      - kafka
    environment:
      # API ENV'S
      WEB_API_PORT: 8000
      WEB_API_ALLOWED_ORIGIN: '["http://localhost:5173"]'

      # DATABASE ENV'S
      MONGO_CONNECT_STRING: mongodb://mongo-db:27017/scalable-chat-app-db

      # SOCKET ENV'S
      SOCKET_ALLOWED_ORIGIN: '["http://localhost:5173"]'

      # REDIS ENV'S
      REDIS_CHANNEL: redis-message-channel

      # KAFKA ENV'S
      KAFKA_GROUP_ID: scalable-chat-app
      KAFKA_BROKERS: kafka-broker:9092
      PROCESS_KAFKA_MESSAGE_LIMIT: 100
      KAFKA_TOPIC: chat-updates
      KAFKA_NO_OF_PARTITIONS: 1

  frontend:
    build:
      context: ./public
      dockerfile: Dockerfile
    container_name: chat-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
