# Dockerfile.backend

FROM node:18

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy app source
COPY . .

# Expose port (adjust if needed)
EXPOSE 8000

# Start app
CMD ["node", "index.js"]
