apiVersion: v1
kind: Service
metadata:
  name: chat-backend
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30002     # or any port between 30000–32767
  type: NodePort
